name: Run Scheduled Scripts

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Decode the service account key and save it as a file
    - name: Decode Service Account Key
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" | base64 --decode > service_account_key.json

    # Step 5: Export secrets as environment variables
    - name: Set environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
        echo "SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

    # Step 6: Run the weather script
    - name: Run weather script
      run: python api/weather.py

    # Step 7: Run the calendar script
    - name: Run calendar script
      run: python api/gcalendar.py

